### Get all posts
GET http://localhost:3001/api/posts

### Get a single post by ID
GET http://localhost:3001/api/posts/1

### Get comments for a post ID
GET http://localhost:3001/api/posts/1/comments

### Create a new post
POST http://localhost:3001/api/posts
Content-Type: application/json

{
    "title": "The Silent Language of Trees",
    "text": "Did you know trees communicate? Far from being isolated entities, trees form intricate networks underground through fungi, often called the Wood Wide Web.",
    "maxComments": 5
}

### Create a comment
POST http://localhost:3001/api/posts/9/comments
Content-Type: application/json

{
    "text": "This is truly captivating! The concept of a Wood Wide Web is incredible and reminds us just how much more there is to learn about nature and the hidden interconnections we often do not see."
}

### Update a comment
PUT http://localhost:3001/api/comments/28
Content-Type: application/json

{
    "text": "Wow, this is such a beautiful reminder of nature intelligence! It is amazing to think about the complex communication happening beneath our feet."
}

### Delete a comment
DELETE http://localhost:3001/api/comments/28

### Delete a post
DELETE http://localhost:3001/api/posts/10

### Mark a comment as interesting
POST http://localhost:3001/api/comments/23/interesting

### Unmark a comment as interesting
DELETE http://localhost:3001/api/comments/23/interesting

### User APIs

### Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "alberto",
    "password": "albertoAdmin"
}

### TOTP 2FA login (admin only)
### Note: "code" is generated by your authenticator app
### Please, use this secret: LXBSMDTMSP2I5XFXIYRGFVWSFI
POST http://localhost:3001/api/login-totp
Content-Type: application/json

{
    "code": "725834"
}

### Logout
DELETE http://localhost:3001/api/sessions/current

### Check current session
GET http://localhost:3001/api/sessions/current
